### ISSUE TITLE
Sonoff Zigbee Dongle Plus Error

### ISSUE THREAD

**Issue by KrX3D** [Koenkk/Z-Stack-firmware#346]
Hello,

i got an Sonoff Zigbee Dongle Plus which i flashed with CC1352P2_CC2652P_launchpad_coordinator_20211217.hex and Flash Programmer 2 which worked.

But i cant get the Stick to work now, i tried it on

- Unraid Server -> Home Assistant VM
- Unraid Server -> IoBroker Docker
- Raspberry -> Home Assistant OS

but i always get the same error, here the one from Home Assistant:

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] config.sh: executing... 
[19:23:24] INFO: Both 'network_key' and 's0_legacy_key' are set and match. All ok.
[19:23:30] INFO: Virtual Machine not detected, enabling soft-reset
[cont-init.d] config.sh: exited 0.
[cont-init.d] structure.sh: executing... 
[cont-init.d] structure.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[19:23:34] INFO: Successfully send discovery information to Home Assistant.
2022-01-08T18:23:37.837Z DRIVER   ███████╗ ██╗    ██╗  █████╗  ██╗   ██╗ ███████╗             ██╗ ███████╗
                                  ╚══███╔╝ ██║    ██║ ██╔══██╗ ██║   ██║ ██╔════╝             ██║ ██╔════╝
                                    ███╔╝  ██║ █╗ ██║ ███████║ ██║   ██║ █████╗   █████╗      ██║ ███████╗
                                   ███╔╝   ██║███╗██║ ██╔══██║ ╚██╗ ██╔╝ ██╔══╝   ╚════╝ ██   ██║ ╚════██║
                                  ███████╗ ╚███╔███╔╝ ██║  ██║  ╚████╔╝  ███████╗        ╚█████╔╝ ███████║
                                  ╚══════╝  ╚══╝╚══╝  ╚═╝  ╚═╝   ╚═══╝   ╚══════╝         ╚════╝  ╚══════╝
2022-01-08T18:23:37.852Z DRIVER   version 8.9.2
2022-01-08T18:23:37.854Z DRIVER   
2022-01-08T18:23:38.059Z CONFIG   version 8.9.2
2022-01-08T18:23:41.115Z CNTRLR   querying controller IDs...
2022-01-08T18:23:42.951Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2022-01-08T18:23:44.074Z CNTRLR   Failed to execute controller command after 2/3 attempts. Scheduling next try i
                                  n 1100 ms.
2022-01-08T18:23:46.233Z DRIVER   Failed to initialize the driver: ZWaveError: Timeout while waiting for an ACK 
                                  from the controller (ZW0200)
                                      at Driver.sendMessage (/usr/src/node_modules/zwave-js/src/lib/driver/Drive
                                  r.ts:3354:23)
                                      at ZWaveController.identify (/usr/src/node_modules/zwave-js/src/lib/contro
                                  ller/Controller.ts:677:33)
                                      at Driver.initializeControllerAndNodes (/usr/src/node_modules/zwave-js/src
                                  /lib/driver/Driver.ts:978:26)
                                      at Immediate.<anonymous> (/usr/src/node_modules/zwave-js/src/lib/driver/Dr
                                  iver.ts:858:16)
Error in driver ZWaveError: Failed to initialize the driver: ZWaveError: Timeout while waiting for an ACK from the controller (ZW0200)
    at Driver.sendMessage (/usr/src/node_modules/zwave-js/src/lib/driver/Driver.ts:3354:23)
    at ZWaveController.identify (/usr/src/node_modules/zwave-js/src/lib/controller/Controller.ts:677:33)
    at Driver.initializeControllerAndNodes (/usr/src/node_modules/zwave-js/src/lib/driver/Driver.ts:978:26)
    at Immediate.<anonymous> (/usr/src/node_modules/zwave-js/src/lib/driver/Driver.ts:858:16) (ZW0100)
    at Immediate.<anonymous> (/usr/src/node_modules/zwave-js/src/lib/driver/Driver.ts:875:6)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 100,
  context: undefined,
  transactionSource: undefined
}
Shutting down
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.`

here from iobroker:

`
2022-01-08 17:43:46.854  - [31merror[39m: zwave2.0 (2199) Failed to initialize the driver: ZWaveError: Timeout while waiting for an ACK from the controller (ZW0200)
    at Driver.sendMessage (/opt/iobroker/node_modules/zwave-js/src/lib/driver/Driver.ts:3390:23)
    at ZWaveController.identify (/opt/iobroker/node_modules/zwave-js/src/lib/controller/Controller.ts:677:33)
    at Driver.initializeControllerAndNodes (/opt/iobroker/node_modules/zwave-js/src/lib/driver/Driver.ts:978:26)
    at Immediate.<anonymous> (/opt/iobroker/node_modules/zwave-js/src/lib/driver/Driver.ts:858:16) (ZW0100)
2022-01-08 17:43:46.854  - [31merror[39m: zwave2.0 (2199) Restarting the adapter in a second...
2022-01-08 17:43:47.855  - [32minfo[39m: zwave2.0 (2199) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
2022-01-08 17:43:48.044  - [32minfo[39m: host.KrX-NaS instance system.adapter.calendar.0 started with pid 2282
2022-01-08 17:43:48.359  - [32minfo[39m: zwave2.0 (2199) Shutting down driver...
2022-01-08 17:43:48.396  - [32minfo[39m: host.KrX-NaS instance system.adapter.zwave2.0 terminated with code 156 (START_IMMEDIATELY_AFTER_STOP)
2022-01-08 17:43:48.397  - [32minfo[39m: host.KrX-NaS Restart adapter system.adapter.zwave2.0 because enabled
2022-01-08 17:43:48.891  - [32minfo[39m: net-tools.0 (2250) Port scan finished
2022-01-08 17:43:48.900  - [33mwarn[39m: net-tools.0 (2250) State "net-tools.0.localhost.ports" has no existing object, this might lead to an error in future versions
2022-01-08 17:43:49.427  - [32minfo[39m: host.KrX-NaS instance system.adapter.zwave2.0 started with pid 2294
2022-01-08 17:43:51.275  - [32minfo[39m: zwave2.0 (2294) starting. Version 2.4.2 in /opt/iobroker/node_modules/iobroker.zwave2, node: v14.18.2, js-controller: 3.3.22
2022-01-08 17:43:52.044  - [32minfo[39m: host.KrX-NaS instance system.adapter.smartthings.0 started with pid 2315
2022-01-08 17:43:53.187  - [32minfo[39m: smartthings.0 (2315) starting. Version 0.0.2 in /opt/iobroker/node_modules/iobroker.smartthings, node: v14.18.2, js-controller: 3.3.22
2022-01-08 17:43:53.508  - [32minfo[39m: smartthings.0 (2315) 1 devices detected
2022-01-08 17:43:56.173  - [31merror[39m: zwave2.0 (2294) Failed to initialize the driver: ZWaveError: Timeout while waiting for an ACK from the controller (ZW0200)
    at Driver.sendMessage (/opt/iobroker/node_modules/zwave-js/src/lib/driver/Driver.ts:3390:23)
    at ZWaveController.identify (/opt/iobroker/node_modules/zwave-js/src/lib/controller/Controller.ts:677:33)
    at Driver.initializeControllerAndNodes (/opt/iobroker/node_modules/zwave-js/src/lib/driver/Driver.ts:978:26)
    at Immediate.<anonymous> (/opt/iobroker/node_modules/zwave-js/src/lib/driver/Driver.ts:858:16) (ZW0100)`

**Comment by dsantos21** [comment]
Are you sure those are the right logs (about zigbee)? Looks like they are pointing to a zwave problem.

**Comment by KrX3D** [comment]
thanks for pointing that out. Home assistant showed zwave after i pluged the stick in

![Unbenannt](https://user-images.githubusercontent.com/18599852/148680867-46c58459-b957-42b8-9717-7df1f41f9083.PNG)

so i thought that this integration is needed.

now i installed Zigbee2MQTT and it works. Thanks
