### ISSUE TITLE
ZBDongle-P Disconnecting from Home Assistant With Latest Firmware

### ISSUE THREAD

**Issue by johnlento** [Koenkk/Z-Stack-firmware#434]
Have been seeing a lot of these issues lately, not totally sure if its firmware or how to debug further. But the coordinator seems to be disconnecting frequently from my Raspberry Pi running Home Assistant. It is on an extension cable and connected to a powered hub. Any help would be appreciated. This is a ZBDongle-P with ~150 devices.

`2023-03-10 13:01:43.403 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall light.turn_on (c:adapt_lgt:b'yO?H':interval:b'`v'): entity_id=['light.texas_instruments_cc1352_cc2652_z_stack_3_30_build_20221226_family_room_flood_lights_zha_group_0x0002'], params=transition=1.0, brightness=255, color_temp=182, color_temp_kelvin=5470>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1826, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1845, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 686, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 961, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 726, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 572, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/usr/src/homeassistant/homeassistant/components/zha/light.py", line 1164, in async_turn_on
    await super().async_turn_on(**kwargs)
  File "/usr/src/homeassistant/homeassistant/components/zha/light.py", line 332, in async_turn_on
    result = await self._level_channel.move_to_level_with_on_off(
  File "/usr/local/lib/python3.10/site-packages/zigpy/zcl/__init__.py", line 324, in request
    return await self._endpoint.request(
  File "/usr/local/lib/python3.10/site-packages/zigpy/group.py", line 57, in request
    await self.application.send_packet(
  File "/usr/local/lib/python3.10/site-packages/zigpy_znp/zigbee/application.py", line 1033, in send_packet
    response = await self._send_request_raw(
  File "/usr/local/lib/python3.10/site-packages/zigpy_znp/zigbee/application.py", line 843, in _send_request_raw
    raise DeliveryError("Coordinator is disconnected, cannot send request")
zigpy.exceptions.DeliveryError: Coordinator is disconnected, cannot send request`

**Comment by johnlento** [comment]
This is still occurring on the latest 20230410. I am also seeing:

File "/usr/local/lib/python3.10/site-packages/zigpy_znp/zigbee/application.py", line 654, in _watchdog_loop
